### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by RubanDurai** [TheCaduceus/Link-Bypasser-Bot#2]
![IMG_20220928_175834](https://user-images.githubusercontent.com/77948100/192778637-e3d74f8b-420f-426d-bc5d-b5dcc2c07e2d.jpg)

**Comment by TheCaduceus** [comment]
**@rubandurai27 Bot repository is not made for any specific platform like Heroku. You can follow the deployment docs given by platform to deploy it.**

**Comment by RubanDurai** [comment]
How to deploy via GitHub actions
